text_area = '/html/body/main/div[1]/div[2]/div/div[2]/div[1]/div/article/div/div/div[2]/div/section/div/div[1]/div[2]/div/div/div/textarea'
send = '.submit-submission'
sign_in = 'ember471'
input_email = 'id_login_email'
input_password = 'id_login_password'
sign_button = '.sign-form__btn.button_with-loader'
correct_answer = '.smart-hints__hint'
solve_again_button = '.again-btn.white'
alert_confirm = '/html/body/div[5]/div/div/footer/button[1]'
link_8='https://stepik.org/lesson/236905/step/1'
link_7='https://stepik.org/lesson/236904/step/1'
link_6='https://stepik.org/lesson/236903/step/1'
link_5='https://stepik.org/lesson/236899/step/1'
link_4='https://stepik.org/lesson/236898/step/1'
link_3='https://stepik.org/lesson/236897/step/1'
link_2='https://stepik.org/lesson/236896/step/1'
link_1='https://stepik.org/lesson/236895/step/1'



